from Tkinter import *
root=Tk()
def displayEntries():
    Label(root,text=e1.get()).grid(row=3)
    Label(root,text=e2.get()).grid(row=4)
root=Tk()
Label(root,text="Pig").grid(row=0,column=0)
Label(root,text="Oink").grid(row=1,column=0)
e1=Entry(root)
e2=Entry(root)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
Button(root,text="Display Entries",command=displayEntries).grid(row=2,column=0)
Button(root,text="Quit",command=root.destroy).grid(row=2,column=1)
mainloop()
